<a href="https://colab.research.google.com/github/DavidAdelG/DataAnalysis/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([5.05528123e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.64108274e-066, 1.16188963e+165, 5.28206026e-091,
       1.10618148e-046, 4.34243033e-315])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:

np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
matrix = np.empty(10)
print(matrix)

[2.e-323 0.e+000 1.e-323 1.e-323 4.e-323 5.e-324 5.e-324 4.e-323 5.e-324
 4.e-323]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
matrix = np.random.randint(10,49,9)
print(matrix)

[37 30 22 23 40 18 43 39 17]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
matrix = np.random.randint(0,8,9)
print(matrix)

rev_matrix = matrix[::-1]
print(rev_matrix)

[4 7 6 7 5 2 0 3 4]
[4 3 0 2 5 7 6 7 4]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.random.randint(0,8,9).reshape(3,3)
print(matrix)

[[2 2 6]
 [2 3 1]
 [6 7 1]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
matrix = np.random.randint(1,999,27).reshape(3,3,3)
print(matrix)

[[[601 311 129]
  [108 198 143]
  [168 327 214]]

 [[348 496 924]
  [830 410 825]
  [321 429 970]]

 [[742 227 383]
  [251 694 811]
  [272 416 870]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
matrix = np.random.randint(1,100000,100).reshape(10,10)
print(matrix)
print(np.max(matrix))
print(np.min(matrix))

[[38682 40195 84271 85188 94550 91985 86827 64139 76793 49928]
 [19007 93761 10621 67075 58771 57291 68632 77805  5717  6705]
 [29688 83493 23681  1226   735 10765 86234  6820 16339 16700]
 [71692 48464 72750 47359 98324  7612 59836 29746 63814 96786]
 [98137 71644 69182 58574 67062 54949 89348 47160 75321 61206]
 [47375 57371 73708 76760 37364 20207 38773 60503 96425 50365]
 [44967 16184 94284 46928 76584 68525 13695 43393 78463 18664]
 [ 9087 11972 79126 60912 47403 52792 91945 95283 56567   803]
 [65497 71028 96050 54550 80489 35782  5405 75772 97214 13842]
 [90368 20339 45748 72402 96452 64413 85359 86609 55284 25543]]
98324
735


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
matrix = np.random.rand(1,10,30)
print(np.mean(matrix))

0.49627664760256174


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

NameError: ignored

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.zeros((5,5))

np.fill_diagonal(matrix[1:],[1,2,3,4])

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8))
for i in range(8):
  for j in range(8):
    if (i+j) % 2 == 0:
      matrix[i,j] = 1

print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
matrix = np.random.randint(1,100,336).reshape(6,7,8)

index = np.unravel_index(100, matrix.shape)

print("the index of the 100th element is: ",index)

the index of the 100th element is:  (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
matrix = np.array([1,0])
np.tile([1,0],(8,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.randint(1,10,25).reshape(5,5)
mean = np.mean(matrix)
std_dev = np.std(matrix)

Nmatrix = (matrix - mean) / std_dev

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(Nmatrix)

Original Matrix:
[[4 9 5 8 1]
 [4 3 1 7 4]
 [4 5 2 8 4]
 [4 5 8 9 6]
 [1 4 4 4 8]]

Normalized Matrix:
[[-0.36841051  1.72483102  0.0502378   1.30618272 -1.62435543]
 [-0.36841051 -0.78705882 -1.62435543  0.88753441 -0.36841051]
 [-0.36841051  0.0502378  -1.20570712  1.30618272 -0.36841051]
 [-0.36841051  0.0502378   1.30618272  1.72483102  0.4688861 ]
 [-1.62435543 -0.36841051 -0.36841051 -0.36841051  1.30618272]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 128)]
Red Component: [255   0   0]
Green Component: [  0 255   0]
Blue Component: [  0   0 255]
Alpha Component: [255 255 128]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
m5 = np.random.randint(1,10,15).reshape(5,3)
m3 = np.random.randint(1,10,6).reshape(3,2)
print(np.dot(m5,m3))

[[ 42  84]
 [ 65  93]
 [ 66 123]
 [ 55  69]
 [ 48  72]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
matrix = np.array([1, 2, 3, 4, 5, -6, 7, 8, 9, 10, 11, 22, -300])

for i in range(len(matrix)):
    if 3 < matrix[i] < 8:
        matrix[i] = -matrix[i]
    elif -8 < matrix[i] < -3:
        matrix[i] = abs(matrix[i])

print(matrix)

[   1    2    3   -4   -5    6   -7    8    9   10   11   22 -300]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
all the 5 are legal expressions

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
division by zero error
division by zero error
empty array

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
float_array = np.array([-2.3, 1.5, -3.8, 4.2, -5.7])
rounded_array = np.where(float_array >= 0, np.ceil(float_array), np.floor(float_array))

print(rounded_array)

[-3.  2. -4.  5. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
matrix = np.array([1,5,9,7,5,3,6,8,4])
matrix2 = np.array([3,2,5,6,49,87,4,1,59,8])
print(np.intersect1d(matrix,matrix2))

[1 3 4 5 6 8]
the common values between these two arrays is {1, 3, 4, 5, 6, 8}


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
old_settings = np.seterr(all='ignore')

# Restore the original warning settings
np.seterr(**old_settings)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import numpy as np
import datetime

today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

today_np = np.datetime64(today)
yesterday_np = np.datetime64(yesterday)
tomorrow_np = np.datetime64(tomorrow)

print("Yesterday:", yesterday_np)
print("Today:", today_np)
print("Tomorrow:", tomorrow_np)


Yesterday: 2023-09-27
Today: 2023-09-28
Tomorrow: 2023-09-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np
import datetime

start_date = datetime.date(2016, 7, 1)
end_date = datetime.date(2016, 7, 31)

date_range = np.arange(start_date, end_date + datetime.timedelta(days=1))

print(date_range)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1,2,3], dtype = float)
B = np.array([4,5,6], dtype = float)

result = np.empty_like(A)

np.add(A, B, out = result)
np.negative(A, out = A)
np.divide(A, 2, out = A)
np.multiply(result, A, out = result)

print(result)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
matrix = np.random.rand(5)*10
integer_part = matrix.astype(int)
print(integer_part)

[0 8 1 0 1]


In [ ]:
matrix = np.random.rand(5)*10
integer_part = np.floor(matrix).astype(int)
print(integer_part)

[3 4 3 9 0]


In [ ]:
matrix = np.random.rand(5)*10
integer_part = np.trunc(matrix).astype(int)
print(integer_part)

[5 9 8 2 5]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.random.randint(0,4,5)
print(np.tile(matrix,5).reshape(5,5))

[[3 3 3 2 2]
 [3 3 3 2 2]
 [3 3 3 2 2]
 [3 3 3 2 2]
 [3 3 3 2 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def gen():
  for i in range(10):
    yield i

vector = np.array(list(gen()))
print(vector)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0,1,12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.randint(1,10,10)
print(np.sort(vector))

[1 2 2 3 3 6 8 8 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
array = np.array([1,2,3,4,5])
print(sum(array))

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(1,5,10)
B = np.random.randint(1,5,10)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
array = np.array([1,2,3,4,5])
array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
matrix = np.random.randint(1,10,10)
count = 0
print(matrix)

for i in matrix:
  if i == np.max(matrix):
    break
  else:
    count += 1

matrix[count] = 0

print(matrix)

[2 2 3 1 7 1 6 9 4 3]
[2 2 3 1 7 1 6 0 4 3]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
matrix = np.random.randint(1,123,10)
for i in matrix:
  print(i)

117
114
76
19
121
112
31
97
2
72


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class array:
  name = ""

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
matrix1 = np.random.randint(1,10,25).reshape(5,5)
matrix2 = np.random.randint(1,10,25).reshape(5,5)
DP = np.dot(matrix1, matrix2)
Diagonal = np.diagonal(DP)

print("\nMatrix1: \n",matrix1)
print("\nMatrix2: \n",matrix2)
print("\nDot Product: \n",DP)
print("\nDiagonal: \n",Diagonal)


Matrix1: 
 [[6 1 4 8 5]
 [7 3 5 9 4]
 [1 4 4 7 4]
 [6 9 6 6 1]
 [9 1 2 6 5]]

Matrix2: 
 [[5 9 7 2 6]
 [4 6 6 6 3]
 [4 5 2 1 3]
 [3 1 9 4 9]
 [9 2 3 6 4]]

Dot Product: 
 [[119  98 143  84 143]
 [130 123 170  97 163]
 [ 94  68 114  82 109]
 [117 146 165 102 139]
 [120 113 142  80 137]]

Diagonal: 
 [119 123 114 102 137]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
original_vector = np.array([1, 2, 3, 4, 5])

new_vector = np.zeros(3 * (len(original_vector) - 1) + len(original_vector), dtype=int)
new_vector[::4] = original_vector

print(new_vector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0 6]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)